repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/psf/black
    rev: 22.10.0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        name: black
        types: [ python ]
        language_version: python # Should be a command that runs python3.6+

  # https://www.flake8rules.com/
  # https://flake8.pycqa.org/en/latest/user/options.html#index-of-options
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [
            "flake8-comprehensions",
            "flake8-mutable",
            "flake8-print",
            "flake8-simplify",
        ]
        name: flake8
        types: [ python ]
        # Flake8 currently does not support pyproject.toml so we will pass settings via args
        args: [
            "--ignore=E203,E501,W503",
            "--max-complexity=12",
        ]
