version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
       db:
         condition: service_healthy
    command: uvicorn simple_example.web_app_example.main:app_setup --host 0.0.0.0 --port 8000
    env_file:
      - ./simple_example/.env
 
  db:
    image: postgres
    restart: always
    hostname: simple_example_database
    env_file:
      - ./simple_example/.env
    expose:
      - 5432
    ports:
      - 5435:5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
